### ISSUE TITLE
Method set() with type float not found on target class class warning in log

### ISSUE THREAD

**Issue by oliverhausler** [DreaminginCodeZH/MaterialProgressBar#10]
I see the following warning in the log:

10-29 11:31:31.257 31494-31494/cc.closeup.android D/ProgressBar: updateDrawableBounds: mProgressDrawable.setBounds()
10-29 11:31:31.262 31494-31494/cc.closeup.android W/PropertyValuesHolder: Method set() with type float not found on target class class me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable$RectTransformX

I haven't coded this myself, but I assume it's an issue within the library, so I wanted to log it. If you need further info let me know what you want me to look at.

**Comment by zhanghai** [comment]
I've also seen this warning on old platforms as Android 4.1 some time ago, but with latest 1.1.4 this library worked without any problem, so I just moved on to some other work.

If you have observed something going wrong, or found out the cause of this warning, please let me know.

**Comment by oliverhausler** [comment]
I can see this on both, 4.2 and 4.4 devices, but nothing seems to be wrong.

**Comment by zhanghai** [comment]
Should be a warning issued on pre-Lollipop for `PropertyValuesHolder` with `null` property name.

As the backport of this library follows the framework implementation of `ObjectAnimator.ofFloat()` which also creates `PropertyValuesHolder` with `null` property name, I'm not going to fix this.

**Comment by webmaster128** [comment]
I am having this warning on Android 5.0.2 as well. Right now, I don't see any problems with it. It is just irritating.

I am running `me.zhanghai.android.materialprogressbar:library:1.1.4`.

**Comment by rpgdev** [comment]
I know this is closed but I'm having this on Android 5.1.0 too:
 W/PropertyValuesHolder: Method set() with type float not found on target class class me.zhanghai.android.materialprogressbar.IndeterminateHorizontalProgressDrawable$RectTransformX

It's just a warning and the progressbar works fine but it's annoying. Is there a way to workaround it so that the warning doesn't show?

**Comment by zhanghai** [comment]
I guess it should be coming from [`ObjectAnimatorCompat.ofFloat(target, null, "scaleX", PATH_INDETERMINATE_HORIZONTAL_RECT1_SCALE_X);`](https://github.com/DreaminginCodeZH/MaterialProgressBar/blob/9ae635a4964c5a68dd3d29b0f60b5da5469d9282/library/src/main/java/me/zhanghai/android/materialprogressbar/Animators.java#85), which called with a propertyName of `null` and thus the `set()` call.

But I don't know how the framework vector drawable get around this.
