### ISSUE TITLE
how change progress color?

### ISSUE THREAD

**Issue by vihuela** [DreaminginCodeZH/MaterialProgressBar#15]

**Comment by zhanghai** [comment]
As mentioned in README, you can use `app:mpb_tint` for color other than `?colorAccent`.

**Comment by WilsonKifua** [comment]
android:tint it worked for me.

**Comment by zhanghai** [comment]
But won't work below L. Beware!

**Comment by bobymicroby** [comment]
And how do you change it bellow L ? 
P.S by code, not with xml

**Comment by zhanghai** [comment]
In Java, simply calling set*Tint() will suffice, it is overridden; in XML, you should use app:mpb_tint.

**Comment by bobymicroby** [comment]
Hmm..the method doesn't pop for   ```MaterialProgressBar alert_preloader;```
![screenshot from 2017-04-16 13-37-29](https://cloud.githubusercontent.com/assets/927575/25070540/1d922408-22aa-11e7-8054-554e692a583a.png)

**Comment by zhanghai** [comment]
Well, I mean set*Tint() then, they affect primary, secondary and background progress, respectively.

**Comment by bobymicroby** [comment]
Well..when i tried ```setProgressTintList``` i received the notification that it will not be tinted bellow L ...  All the set*Tint methods will give the same warning.

**Comment by zhanghai** [comment]
That's another issue - the progress bar's current drawable is not one of the library's. Your code on creating the ProgressBar is needed to know why, but I strongly recommend you to use Inflator and XML for creating a MaterialProgressBar instance.

**Comment by bobymicroby** [comment]
Trouble is that the color is  based on dynamic palette... and i want to reuse the MaterialProgressBar instances because everything is in recyclerviews... i will try to figure it out. Thanks for the help !

**Comment by farruxx** [comment]
I found that it is Androids issue, any other progress bars also cannot handle drawable changing correctly
