### ISSUE TITLE
not working below lollipop after updating support libs to 23.2.0 and greater

### ISSUE THREAD

**Issue by raviteja83** [DreaminginCodeZH/MaterialProgressBar#18]
I tested it on kikat.It is not throwing any error but it is not visible.I didn't enable vector.useSupportLibrary = true in build gradle file.My gradle plugin version 2.1.0-alpha2.

**Comment by zhanghai** [comment]
Cannot reproduce with API 22 and support 23.2.1, please provide more detail.

**Comment by zhanghai** [comment]
Cannot reproduce.
