### ISSUE TITLE
Rendering Problems

### ISSUE THREAD

**Issue by migelfn** [DreaminginCodeZH/MaterialProgressBar#19]
These errors appears on layout preview/design view, is there a way to fix this?

```
Couldn't resolve resource @style/Widget.MaterialProgressBar.ProgressBar.Small
"horizontal" in attribute "mpb_progressStyle" is not a valid integer
```

**Comment by zhanghai** [comment]
Reproduced. An "Invalidate cache and restart" did not work.

Personally I don't know why, may be a regression in Android Studio that styles from dependent libraries cannot be loaded?

But it works normally in production.

**Comment by smaznet** [comment]
i used 1 instead `horizontal`
in my xml

``` 
<me.zhanghai.android.materialprogressbar.MaterialProgressBar
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:mpb_useIntrinsicPadding="false"
            app:mpb_progressStyle="1"
            android:id="@+id/loadMaterialPBar"
            android:visibility="invisible"
            style="@style/Widget.AppCompat.ProgressBar.Horizontal"
android:layout_marginBottom="1dp"
            android:minHeight="3dp" />
```

**Comment by mihudevcom** [comment]
It seems to be working just fine with Android Studio 2.3.1. @DreaminginCodeZH can you confirm this?

**Comment by zhanghai** [comment]
Yes I see no error now -- it is blank, but that's another enchancement to do. Thanks @mihudevcom!
