### ISSUE TITLE
Remove vertical padding from horizontal ProgressBar

### ISSUE THREAD

**Issue by aat-antoine** [DreaminginCodeZH/MaterialProgressBar#20]
Is there a way to keep material design and remove this useless padding in horizontal progress bar ?

**Comment by zhanghai** [comment]
It's a feature of this library, as in README:

> Why MaterialProgressBar?
> ...
> Able to remove the intrinsic padding of framework ProgressBar.
> ...
> And more size and no-padding variants in styles.xml

You can also check out the [sample activity layout](https://github.com/DreaminginCodeZH/MaterialProgressBar/blob/master/sample/src/main/res/layout/main_activity.xml), and you'll find these lines:

```
            <me.zhanghai.android.materialprogressbar.MaterialProgressBar
                android:id="@+id/horizontal_progress_toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom"
                android:progress="30"
                android:secondaryProgress="60"
                app:mpb_progressStyle="horizontal"
                app:mpb_useIntrinsicPadding="false"
                app:mpb_showTrack="false"
                style="@style/Widget.MaterialProgressBar.ProgressBar.Horizontal.NoPadding" />
```

Remove the show track line if you want the progress bar track.

**Comment by aat-antoine** [comment]
Sorry, i had not read this part. Thx
