### ISSUE TITLE
Determinate circular drawable is not yet supported

### ISSUE THREAD

**Issue by Nolanus** [DreaminginCodeZH/MaterialProgressBar#24]
Are there any plans of adding determinate circular progress indicator?

**Comment by zhanghai** [comment]
Well, framework did not have the circular determinate progess drawable, and the spec of Material Design has only given one example on animating the indeterminate one to completion. In application It is not often seen in Material Designed apps as well. So I did not implement it.

If you have any thought on why it should be added, please write it down here.

**Comment by zokipirlo** [comment]
[Here is a circular determinate progress specification](https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators)

You can also see it in the "Fit" application for a progress through the day.

It's more pretty to put determinate progress in circular style when using it in grid layout.

**Comment by webmaster128** [comment]
@Nolanus @zokipirlo Could you have a look if #51 fits your needs?

**Comment by webmaster128** [comment]
Thanks again @DreaminginCodeZH for cleaning up my implementation and releasing this. I just wanted to let you know that I successfully integrated MaterialProgressBar 1.4.1 and the determinate circular progress indicator into two projects:

* [dialogs-for-android](https://github.com/DialogsForAndroid/dialogs-for-android) using Android's ProgressBar and MaterialProgressBar's drawables
* Kullo using MaterialProgressBar from xml without any Java code apart from setting Progress value
