### ISSUE TITLE
Library does not support programmatic usage

### ISSUE THREAD

**Issue by Ribesg** [DreaminginCodeZH/MaterialProgressBar#27]
I'm not using XML for layouts in my Android project, and I simply can't use this lib at all.

You can't create a circular `MaterialProgressBar`, it just crashes saying determinate cirular progress bar isn't supported. But you can't set the determinate state before creating the object.

**Comment by Ribesg** [comment]
It looks like if you create a MaterialProgressBar without passing the `PROGRESS_STYLE_CIRCULAR` style, it actually creates an indeterminate circular progress... Weird behaviour, but it works.

**Comment by Ribesg** [comment]
Well I still don't get it. I can't create an horizontal progress bar now. Why doesn't this work?

```
MaterialProgressBar(context, null, R.style.Widget_MaterialProgressBar_ProgressBar_Horizontal_NoPadding)
```

**Comment by zhanghai** [comment]
If you want to create a Material Design ProgressBar programmatically, you can use a regular framework `ProgressBar` and call `setProgressDrawable(new ...Drawable())` on it; or you can create a layout file and inflate it. The `MaterialProgressBar` widget is intended as a shortcut in layout files.
