### ISSUE TITLE
Use intrinsic padding attr is only applied to one drawable

### ISSUE THREAD

**Issue by gnawf** [DreaminginCodeZH/MaterialProgressBar#28]
If you have `mpb_setBothDrawables` set to true, `mpb_useIntrinsicPadding` is only applied to one drawable i.e. the active drawable from `MaterialProgressBar.getDrawable()`

Relevant code https://github.com/DreaminginCodeZH/MaterialProgressBar/blob/master/library/src/main/java/me/zhanghai/android/materialprogressbar/MaterialProgressBar.java#L96-L106

**Comment by zhanghai** [comment]
Thanks! I've been really busy with my finals these days, sorry for the delay.
