### ISSUE TITLE
start and stop indeterminate progress on demand

### ISSUE THREAD

**Issue by wrozwad** [DreaminginCodeZH/MaterialProgressBar#39]
Is there a possibility to show MaterialProgressBar without starting indeterminate progress bar and to start and stop it on demand?

**Comment by zhanghai** [comment]
Maybe you mean toggling between `View.INVISIBLE` and `View.VISIBLE`? Or  some alpha animation?

**Comment by wrozwad** [comment]
Of course it's not a problem to use setVisibility or something like that. I just like to make "awesome looking app" so it'll be great if I can manually start indeterminate animation eg. with 1000 ms delay. Stop animation (eg. by dynamically change width of progress) will be just a nice addon.

**Comment by zhanghai** [comment]
You can call `Animatable.start()` and `Animatable.stop()` for drawables implementing `Animatable`. `ProgressBar` calls `Animatable.start()` automatically so you have to either delay setting the drawable or do some hacking.
