### ISSUE TITLE
visibility="invisible" does nothing / no progress animation when visible

### ISSUE THREAD

**Issue by hormesiel** [DreaminginCodeZH/MaterialProgressBar#41]
I've tried using this lib in two different projects, one is on google play and the other one was just a test project to confirm the problems I had in the former.

1) First problem is that setting the progress bar's visibility to `invisible` does nothing, the progress bar is still as visible as if I set it to `visible`. `gone` works, but I just want to be able to hide/show it without "disturbing" the whole layout so I'd rather use `invisible`.

2) Even when the progress bar is `visible` and using `indeterminate="true"`, it looks like a simple "line". I mean, there's no animation that make it look like a progress, it could just be a plain `View` with a `backgroundColor` and there would be no difference. So how do I trigger the indeterminate progress animation?

Great looking library btw, just too bad I can't get it to work ^^

Here's the code :

**activity_main.xml**

``` xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    tools:context="flawyte.md_progress_test.MainActivity">

    <android.support.design.widget.AppBarLayout
        android:layout_height="wrap_content"
        android:layout_width="match_parent">

        <android.support.v7.widget.Toolbar
            android:layout_height="56dp"
            android:layout_width="match_parent" />

        <View
            android:background="@android:color/white"
            android:layout_height="2dp"
            android:layout_width="match_parent" />

        <me.zhanghai.android.materialprogressbar.MaterialProgressBar
            android:id="@+id/progress"
            android:indeterminate="true"
            android:layout_height="5dp"
            android:layout_width="match_parent"
            android:visibility="invisible"
            app:mpb_progressStyle="horizontal" />

    </android.support.design.widget.AppBarLayout>

    <RelativeLayout
        android:id="@+id/content"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <TextView
            android:background="@color/colorAccent"
            android:id="@+id/button"
            android:layout_centerInParent="true"
            android:layout_height="wrap_content"
            android:layout_width="wrap_content"
            android:padding="32dp"
            android:text="Hello World!"
            android:textColor="@android:color/white" />

    </RelativeLayout>

</android.support.design.widget.CoordinatorLayout>
```

**MainActivity.java**

``` java
package flawyte.md_progress_test;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.ProgressBar;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {
    boolean loading;
    ProgressBar progressBar;

    @Override
    public void onClick(View view) {
        loading = !loading;

        progressBar.setVisibility(loading ? View.VISIBLE : View.INVISIBLE);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        loading = false;
        progressBar = (ProgressBar) findViewById(R.id.progress);

        findViewById(R.id.button).setOnClickListener(this);
    }
}
```

**Comment by zhanghai** [comment]
Cannot reproduce the visibility problem - If I set `android:visibility="invisible"` on the `MaterialProgressBar`s of the sample app, they are successfully hidden. See screenshot.

![2016-08-26 09-47-20](https://cloud.githubusercontent.com/assets/4469895/17991549/4368a778-6b72-11e6-9c89-0e9e84b377e2.png)

As for the intermidate progress bar, please check out the README or the sample app. I noticed that you didn't set `style` which is required for framework `ProgressBar` to behave properly.

https://github.com/DreaminginCodeZH/MaterialProgressBar#using-widget

https://github.com/DreaminginCodeZH/MaterialProgressBar/blob/master/sample/src/main/res/layout/main_activity.xml

**Comment by hormesiel** [comment]
It works now that I've added the missing `style` XML attribute. Both problems are solved. Thanks for your reactivity!
