### ISSUE TITLE
Skipped frames

### ISSUE THREAD

**Issue by prog110** [DreaminginCodeZH/MaterialProgressBar#44]
When the loading bar is displayed on the screen for long, Choreographer informs that there are a lot of frames that are skipped

You see a log entry like this

`I/Choreographer: Skipped 126 frames!  The application may be doing too much work on its main thread.`

This happens only on screens where I display material progress bar

**Comment by zhanghai** [comment]
Any conditions to reproduce it? Didn't see this with the sample app.
