### ISSUE TITLE
Could not find me.zhanghai.android.materialprogressbar

### ISSUE THREAD

**Issue by ejohansson** [DreaminginCodeZH/MaterialProgressBar#45]
Error: Could not find me.zhanghai.android.materialprogressbar:library:1.2.0.
Required by:
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by zhanghai** [comment]
Sorry for the inconvenience, forgot to close and release on Sonatype last night. Should be available within half an hour now.

**Comment by ejohansson** [comment]
No worries, thanks for the update.  👍

**Comment by zhanghai** [comment]
Available on Maven Central now.
