### ISSUE TITLE
CircularProgressDrawable not public

### ISSUE THREAD

**Issue by webmaster128** [DreaminginCodeZH/MaterialProgressBar#55]
The updated README states that CircularProgressDrawable can be used directly from outside but the constuctor is not public. Thus I cannot integrate it into [dialogs-for-android](https://github.com/DialogsForAndroid/dialogs-for-android) the same way as it is done with the other drawables

**Comment by zhanghai** [comment]
It is a mistake; I'll release a new version tomorrow -- it's over midnight now in my timezone :P

**Comment by webmaster128** [comment]
Thanks and good night :)

**Comment by zhanghai** [comment]
Released v1.4.1; Kullo seems a beautiful app BTW, and thanks for you contribution again
