### ISSUE TITLE
Add ability to change circular progressbar width

### ISSUE THREAD

**Issue by ursusursus** [DreaminginCodeZH/MaterialProgressBar#61]
Hi, please add this option , I am making a button with icon in center and circular progressbar around it, and it visually looks bad when progressbar is different width than lines in icon. Afaik I can tell you scale the cancas with width, but Id like to set fixed width

**Comment by zhanghai** [comment]
If you mean the stroke width, sorry but this is against the Material Design guidelines so it won't be implemented here.

But just FYI, you can always copy the implementation and change the value in [BaseSingleCircularProgressDrawable](https://github.com/DreaminginCodeZH/MaterialProgressBar/blob/master/library/src/main/java/me/zhanghai/android/materialprogressbar/BaseSingleCircularProgressDrawable.java#L21).

**Comment by ursusursus** [comment]
Google Play uses this. Maybe consider the class to be more easily extended rather than code copying. Now as I see it, I have to extend BaseProgressLayerDrawable, which takes the drawable array as ctor argument, so thereforce I have to copy BaseSingleCircularProgressDrawable, SingleCircularProgressDrawable, CircularProgressBackgroundDrawable and same goes for extending IndeterminateHorizontalProgressDrawable, which you really cant as drawRing is private etc.

**Comment by ursusursus** [comment]
![2017-07-04 08 43 55](https://user-images.githubusercontent.com/1503402/27823094-33bb9fa2-60a8-11e7-8b5a-1574ae1d095f.png)
![2017-07-04 08 45 34](https://user-images.githubusercontent.com/1503402/27823058-134a0a4c-60a8-11e7-953a-0c2ba4c4505c.png)

**Comment by ursusursus** [comment]
and BaseIndeterminateProgressDrawable is package private so yeah this is not feasibly right now

**Comment by zhanghai** [comment]
You can always drop your class into package of this library, a hack popular with support libraries.

**Comment by ursusursus** [comment]
I know, but I feel it should be a feature of the library, see Google uses it, you can deviate from guidelines when there is a purpose

**Comment by Tolriq** [comment]
@DreaminginCodeZH could you reconsider this feature requests?

While it works in Java, Kotlin is more strict and prevent overriding any of the classes due to (public function exposes its internal return type in Kotlin error and all the package private / protected stuff)
