### ISSUE TITLE
这个不是系统自带吗?

### ISSUE THREAD

**Issue by cv0cv0** [DreaminginCodeZH/MaterialProgressBar#66]
系统默认样式不就是这个吗?

**Comment by zhanghai** [comment]
Please read README before creating issues.

> Why MaterialProgressBar?
>
> - Consistent appearance on Android 4.0+.
> - Correct tinting across platforms.
> - Able to remove the intrinsic padding of framework ProgressBar.
> - Able to hide the progress background of framework horizontal ProgressBar.
> - Able to show a determinate circular progress.
> - Used as a drop-in replacement for framework ProgressBar.
