### ISSUE TITLE
Feedback MaterialProgressBar problem

### ISSUE THREAD

**Issue by tcqq** [DreaminginCodeZH/MaterialProgressBar#67]
Hello thank you for you library, Now I want to change the MaterialProgressBar color with the code, but I did not try to succeed. Could you give an example? Thank you @DreaminginCodeZH

**Comment by tcqq** [comment]
I want set int format the color how should I do?

**Comment by zhanghai** [comment]
Use MaterialProgressBar.setProgressTint, setSecondaryProgressTint and setProgressBackgroundTint. Also make sure the type of your variable for the progress bar is MaterialProgressBar instead of ProgressBar, or your app will crash on lower API levels (framework methods are missing).

**Comment by tcqq** [comment]
I tried, but did not succeed, how should I modify?

            materialProgressBar.setProgressTintList(ColorStateList.valueOf(ContextCompat.getColor(getContext(), R.color.red)));
            materialProgressBar.setSecondaryProgressTintList(ColorStateList.valueOf(ContextCompat.getColor(getContext(), R.color.red)));
            materialProgressBar.setProgressBackgroundTintList(ColorStateList.valueOf(ContextCompat.getColor(getContext(), R.color.red)));

**Comment by tcqq** [comment]
MaterialProgressBar not got setProgressTint、setSecondaryProgressTint and setProgressBackgroundTint

**Comment by zhanghai** [comment]
Ah yes I meant `set*TintList()`, `set*Tint()` is not included in the framework `ProgresssBar` API so not backported as well.

You code above should work, I tested it in sample and it worked.

**Comment by zhanghai** [comment]
One more note. If you are using indeterminate mode, use `setIndeterminateTintList()` instead.

**Comment by tcqq** [comment]
Thankyou, setIndeterminateTintList worked
