### ISSUE TITLE
android.support.v4.content.FileProvider

### ISSUE THREAD

**Issue by felixdivo** [DreaminginCodeZH/MaterialProgressBar#69]
There is a problem with this library and some file provider. I get the following error when I declare a provider by myself:

```
Element provider#android.support.v4.content.FileProvider at AndroidManifest.xml:65:9-74:20 duplicated with element declared at AndroidManifest.xml:55:9-63:20
```

Also see [this](https://stackoverflow.com/questions/42893846/androidmanifest-merge-error-using-fileprovider).

**Comment by michaeltnguyen** [comment]
That is not from this library.  There's no file provider in the manifest.  https://github.com/DreaminginCodeZH/MaterialProgressBar/blob/master/library/src/main/AndroidManifest.xml

You can use manifest merger tags (`tools:replace="android:authorities"`) on your FileProvider, or simply give it a name in your own namespace.

**Comment by zhanghai** [comment]
Thank you @michaeltnguyen !

**Comment by felixdivo** [comment]
Okay, I did the second thing. Sorry for bothering you. I thought it was your Manifest that was shown in the logs but well, apparently it wasn't. ;)
