### ISSUE TITLE
颜色主题怎么设置?

### ISSUE THREAD

**Issue by thirdparty-core** [DreaminginCodeZH/MaterialProgressBar#70]
大神,进度条的颜色怎么设置?

**Comment by zhanghai** [comment]
> 8 tint-related attributes such as `app:mpb_progressTint` and `app:mpb_progressTintMode` are also supported so that they can control the tinting of progress drawables. The default tint color is `?colorControlActivated`, and the default tint mode is `src_in`.

Please read README before posting.
