### ISSUE TITLE
[Enhancement] Permanently spinning determinate circular progress

### ISSUE THREAD

**Issue by smelfungus** [DreaminginCodeZH/MaterialProgressBar#71]
Hi there! Thank you for great library.
It would be very nice to implement one more determinateCircularProgressStyle with always spinning ring with gap decreasing its size with progress.
In current implementation animation just stops when reaching target progress, the idea is to have continuous spinning.
Does it violate Material Design principles?

**Comment by zhanghai** [comment]
Not to say it's a violation, but it is simply not inside the guidelines, and issues remain such as how fast the ring should spin (Can you get a sensible value from the guidelines of another style?). You may need to roll your own implementation in this case, and a PR is welcomed.
