### ISSUE TITLE
cannot find class

### ISSUE THREAD

**Issue by wkq87** [DreaminginCodeZH/MaterialProgressBar#73]
Here is crash log:
`java.lang.RuntimeException:Unable to start activity ComponentInfo{com.sloar.music/com.kabouzeid.gramophone.ui.activities.MainActivity}: android.view.InflateException: Binary XML file line #68: Error inflating class me.zhanghai.android.materialprogressbar.MaterialProgressBar`

And the device info is below
Android version: Android 4.1.1,level 16   ROM:Samsung/full   CPU:armeabi-v7a

**Comment by zhanghai** [comment]
More stacktrace is needed; This only tells us that some exception was thrown by someone during instantiating a MaterialProgressBar instance.
