### ISSUE TITLE
How to be compatible with my local version:25.0.2.

### ISSUE THREAD

**Issue by Sky24n** [DreaminginCodeZH/MaterialProgressBar#74]
Error:Could not find com.android.support:appcompat-v7:26.0.2.
Required by:
    project :base
Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by zhanghai** [comment]
```gradle
compile ('me.zhanghai.android.materialprogressbar') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
compile 'com.android.support:appcompat-v7:25.0.2'
```

**Comment by Sky24n** [comment]
Error:Supplied String module notation 'me.zhanghai.android.materialprogressbar' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

**Comment by Sky24n** [comment]
This is local build：
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
}


 classpath 'com.android.tools.build:gradle:2.3.2'

**Comment by zhanghai** [comment]
Are you building this project locally, or using this library as a dependency? (Because I saw no materialprogressbar in your build.gradle) If you mean the latter one, try this:

```gradle
compile ('me.zhanghai.android.materialprogressbar:library:1.4.2') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
    exclude group: 'com.android.support', module: 'support-annotations'
}
compile 'com.android.support:appcompat-v7:25.3.1'
compile 'com.android.support:support-annotations:25.3.1'
```

The basic idea is to exclude the transitive dependency with new version pulled in by this library, and supply older version manually.

**Comment by Sky24n** [comment]
All right，Thank you very much.
