### ISSUE TITLE
App crashing without any error log when switching from Indeterminate to Determinate

### ISSUE THREAD

**Issue by pratickRoy** [DreaminginCodeZH/MaterialProgressBar#76]
If the ProgressBar is set to Indeterminate and then set to Determinate, the app is crashing. No error logs are showing.
However when changing from Determinate to Indeterminate, it is working as expected.

**Comment by zhanghai** [comment]
> app:mpb_setBothDrawables: Whether both determinate and indeterminate drawables should be set on this progress bar. Defaults to false (for performance). Should be set to true if you want to use both of the backported determinate and indeterminate drawables.
