### ISSUE TITLE
Manifest merger failed!

### ISSUE THREAD

**Issue by Tukmens** [DreaminginCodeZH/MaterialProgressBar#84]
I just started to learn Android development few weeks ago so maybe there's issue with me and not with this library. But whenever I'm trying to use it even in new project Android Studio throws out this error.

`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-22:19 to override.
`

**Comment by zhanghai** [comment]
This library never used `android:appComponentFactory`, so the issue is most likely you and another library included by you both defined `android:appComponentFactory` on the `<application>` element.

**Comment by droidchef** [comment]
I can reproduce this issue in my Android Studio as well.

**Comment by zhanghai** [comment]
@droidchef 

Reading the error message:

> Attribute application:appComponentFactory ... from [com.android.support:support-compat:28.0.0] ... is also present at [androidx.core:core:1.0.0] ...

You are (either directly or indirectly) mixing old Support Libraries with new Android X, so you need to remove the old one. If you are using an old version of this library, try upgrading it to `implementation 'me.zhanghai.android.materialprogressbar:library:1.6.0'` which has been using AndroidX. If some other libraries caused this, try make sure your Jetifier is enabled.

**Comment by iandreyshev** [comment]
@droidchef, I understanding this when read [the post](https://developer.android.com/jetpack/androidx/)

**Comment by zihadrizkyef** [comment]
Then how to solve this? The Issue appears when i implement this library to my project
Now i cannot use your ammazing library because this issue

**Comment by Tukmens** [comment]
I just used an older version of this library. But since I was using it just for learning purposes I had no willingness to find a workaround to run the newest one. But definitely there's a problem with their library since I've tried to run it also on clean AS project without any androidX.

**Comment by zhanghai** [comment]
Please migrate to AndroidX and use the lastest version of this library.

If you really don't want to use AndroidX, you need to stick with v1.4.2 of this library.
