### ISSUE TITLE
Can not change MaterialProgressBar progress color programatically.

### ISSUE THREAD

**Issue by SaurabhGaddelpalliwar** [DreaminginCodeZH/MaterialProgressBar#93]
like,
  progressBarLoad.getIndeterminateDrawable().setColorFilter(Color.parseColor(SharedPreference.getInstance(getActivity()).getString("progressBar", "#d83bff")), android.graphics.PorterDuff.Mode.MULTIPLY);

please tel me you have any solution or any function to change a color of  MaterialProgressBar progress color programatically.

**Comment by zhanghai** [comment]
Please read the README, e.g. `app:mpb_progressTint`.
